2025-08-14 15:31:12,858 - INFO - Starting experiment: ccasf_clifford on wikipedia
2025-08-14 15:31:12,858 - INFO - Device: cuda
2025-08-14 15:31:12,858 - INFO - 
==================================================
2025-08-14 15:31:12,858 - INFO - Run 1/5
2025-08-14 15:31:12,858 - INFO - ==================================================
2025-08-14 15:31:12,861 - INFO - Starting training for wikipedia with C-CASF
2025-08-14 15:31:12,862 - INFO - Configuration: {'dataset_name': 'wikipedia', 'model_name': 'DyGMamba_CCASF', 'use_ccasf': True, 'spatial_dim': 64, 'temporal_dim': 64, 'ccasf_output_dim': 128, 'node_feat_dim': 172, 'edge_feat_dim': 172, 'fusion_method': 'clifford', 'weighted_fusion_learnable': True, 'mlp_hidden_dim': None, 'mlp_num_layers': 2, 'use_rpearl': True, 'use_enhanced_lete': True, 'rpearl_k': 16, 'rpearl_mlp_layers': 2, 'rpearl_hidden': 64, 'lete_p': 0.5, 'lete_layer_norm': True, 'lete_scale': True, 'time_feat_dim': 100, 'channel_embedding_dim': 100, 'patch_size': 2, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.1, 'gamma': 0.5, 'max_input_sequence_length': 64, 'max_interaction_times': 10, 'learning_rate': 0.0001, 'weight_decay': 0.01, 'patience': 20, 'num_epochs': 100, 'batch_size': 200, 'eval_batch_size': 200, 'test_batch_size': 200, 'val_ratio': 0.15, 'test_ratio': 0.15, 'negative_sample_strategy': 'random', 'num_neighbors': 20, 'num_runs': 5, 'load_best_configs': False, 'device': 'cuda', 'num_workers': 8, 'seed': 0, 'data_root': '/home/s2516027/GLCE/processed_data', 'output_root': '/home/s2516027/GLCE/results', 'checkpoint_dir': '/home/s2516027/GLCE/checkpoints', 'log_every': 1, 'eval_every': 5, 'save_model': True, 'verbose': True}
2025-08-14 15:31:12,862 - INFO - Loading wikipedia dataset...
2025-08-14 15:31:13,288 - INFO - Number of nodes: 9228
2025-08-14 15:31:13,288 - INFO - Number of edges: 157475
2025-08-14 15:31:13,288 - INFO - Node feature dimension: 172
2025-08-14 15:31:13,288 - INFO - Edge feature dimension: 172
2025-08-14 15:31:13,288 - INFO - Training interactions: 79202
2025-08-14 15:31:13,288 - INFO - Validation interactions: 23621
2025-08-14 15:31:13,288 - INFO - Test interactions: 23621
2025-08-14 15:31:13,433 - INFO - Creating DyGMamba with C-CASF integration...
2025-08-14 15:31:13,727 - INFO - Model created with 1198558 parameters
2025-08-14 15:31:13,727 - INFO - C-CASF Configuration:
2025-08-14 15:31:13,727 - INFO -   - Spatial dimension: 64
2025-08-14 15:31:13,727 - INFO -   - Temporal dimension: 64
2025-08-14 15:31:13,727 - INFO -   - Output dimension: 128
2025-08-14 15:31:13,727 - INFO -   - Fusion method: clifford
2025-08-14 15:31:13,727 - INFO -   - Using R-PEARL: True
2025-08-14 15:31:13,727 - INFO -   - Using Enhanced LeTE: True
2025-08-14 15:31:14,516 - ERROR - Error in batch 0
Traceback (most recent call last):
  File "/home/s2516027/GLCE/DyGMamba/train_ccasf_link_prediction.py", line 163, in train_epoch
    result = model.compute_src_dst_node_temporal_embeddings(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/GLCE/DyGMamba/models/DyGMamba_CCASF.py", line 259, in compute_src_dst_node_temporal_embeddings
    return self._compute_ccasf_embeddings(src_node_ids, dst_node_ids, node_interact_times, num_samples)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/GLCE/DyGMamba/models/DyGMamba_CCASF.py", line 310, in _compute_ccasf_embeddings
    node_embeddings = self.stampede_framework(graph_data, timestamps)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/anaconda3/envs/glce/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/anaconda3/envs/glce/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/GLCE/DyGMamba/models/CCASF.py", line 543, in forward
    spatial_embeddings = self.spatial_encoder.get_embeddings(graph_data, node_ids)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/GLCE/DyGMamba/models/rpearl_adapter.py", line 308, in get_embeddings
    return self.forward(graph_data, node_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/GLCE/DyGMamba/models/rpearl_adapter.py", line 276, in forward
    normalized = self.output_norm(projected)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/anaconda3/envs/glce/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/anaconda3/envs/glce/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/anaconda3/envs/glce/lib/python3.11/site-packages/torch/nn/modules/normalization.py", line 217, in forward
    return F.layer_norm(
           ^^^^^^^^^^^^^
  File "/home/s2516027/anaconda3/envs/glce/lib/python3.11/site-packages/torch/nn/functional.py", line 2900, in layer_norm
    return torch.layer_norm(
           ^^^^^^^^^^^^^^^^^
RuntimeError: Given normalized_shape=[64], expected input with shape [*, 64], but got input of size[6241, 1]
2025-08-14 15:31:14,519 - ERROR - Error in run 0
Traceback (most recent call last):
  File "/home/s2516027/GLCE/DyGMamba/train_ccasf_link_prediction.py", line 435, in main
    results, model = train_model(config, logger)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/GLCE/DyGMamba/train_ccasf_link_prediction.py", line 326, in train_model
    train_loss = train_epoch(model, train_data, optimizer, criterion, config, logger)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/GLCE/DyGMamba/train_ccasf_link_prediction.py", line 163, in train_epoch
    result = model.compute_src_dst_node_temporal_embeddings(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/GLCE/DyGMamba/models/DyGMamba_CCASF.py", line 259, in compute_src_dst_node_temporal_embeddings
    return self._compute_ccasf_embeddings(src_node_ids, dst_node_ids, node_interact_times, num_samples)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/GLCE/DyGMamba/models/DyGMamba_CCASF.py", line 310, in _compute_ccasf_embeddings
    node_embeddings = self.stampede_framework(graph_data, timestamps)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/anaconda3/envs/glce/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/anaconda3/envs/glce/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/GLCE/DyGMamba/models/CCASF.py", line 543, in forward
    spatial_embeddings = self.spatial_encoder.get_embeddings(graph_data, node_ids)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/GLCE/DyGMamba/models/rpearl_adapter.py", line 308, in get_embeddings
    return self.forward(graph_data, node_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/GLCE/DyGMamba/models/rpearl_adapter.py", line 276, in forward
    normalized = self.output_norm(projected)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/anaconda3/envs/glce/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/anaconda3/envs/glce/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2516027/anaconda3/envs/glce/lib/python3.11/site-packages/torch/nn/modules/normalization.py", line 217, in forward
    return F.layer_norm(
           ^^^^^^^^^^^^^
  File "/home/s2516027/anaconda3/envs/glce/lib/python3.11/site-packages/torch/nn/functional.py", line 2900, in layer_norm
    return torch.layer_norm(
           ^^^^^^^^^^^^^^^^^
RuntimeError: Given normalized_shape=[64], expected input with shape [*, 64], but got input of size[6241, 1]
